In [8]:
import numpy as np

In [10]:
x= np.array([1,2,3,4])
y= np.array([5,6,7])

In [13]:
np.concatenate([x,y])

array([1, 2, 3, 4, 5, 6, 7])

In [14]:
z= np.array([9,10])

In [15]:
np.concatenate([x,y,z])

array([ 1,  2,  3,  4,  5,  6,  7,  9, 10])

In [26]:
k = np.array([[10,11,12],
              [13,14,15],
              [18,19,20]])

In [29]:
np.concatenate([k,k], axis = 1 )

array([[10, 11, 12, 10, 11, 12],
       [13, 14, 15, 13, 14, 15],
       [18, 19, 20, 18, 19, 20]])