In [1]:
import numpy as np

In [4]:
m = np.arange(16).reshape(4,4)

In [5]:
m

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15]])

In [7]:
alt, ust = np.vsplit(m,[2])

In [8]:
alt

array([[0, 1, 2, 3],
       [4, 5, 6, 7]])

In [9]:
ust

array([[ 8,  9, 10, 11],
       [12, 13, 14, 15]])

In [10]:
np.hsplit(m,[1])

[array([[ 0],
        [ 4],
        [ 8],
        [12]]), array([[ 1,  2,  3],
        [ 5,  6,  7],
        [ 9, 10, 11],
        [13, 14, 15]])]

In [11]:
sag,sol = np.hsplit(m,[2])

In [12]:
sag

array([[ 0,  1],
       [ 4,  5],
       [ 8,  9],
       [12, 13]])

In [13]:
sol

array([[ 2,  3],
       [ 6,  7],
       [10, 11],
       [14, 15]])

In [14]:
m

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15]])

In [19]:
m[2,2] = 100.59

In [20]:
m

array([[  0,   1,   2,   3],
       [  4,   5,   6,   7],
       [  8,   9, 100,  11],
       [ 12,  13,  14,  15]])

In [41]:
a= np.arange(20,40)

In [42]:
a

array([20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33, 34, 35, 36,
       37, 38, 39])

In [43]:
a[al_getir]

array([21, 23, 25])

In [24]:
a[3::5]

array([23, 28, 33, 38])

In [25]:
a[5:]

array([25, 26, 27, 28, 29, 30, 31, 32, 33, 34, 35, 36, 37, 38, 39])

In [26]:
m

array([[  0,   1,   2,   3],
       [  4,   5,   6,   7],
       [  8,   9, 100,  11],
       [ 12,  13,  14,  15]])

In [27]:
m[3,3]

15

In [29]:
m[2::1,3::1]

array([[11],
       [15]])

In [30]:
alt_a= m[0:3,1:3]
alt_a

array([[  1,   2],
       [  5,   6],
       [  9, 100]])

In [31]:
alt_a[0,1]=15

In [32]:
alt_a

array([[  1,  15],
       [  5,   6],
       [  9, 100]])

In [33]:
m

array([[  0,   1,  15,   3],
       [  4,   5,   6,   7],
       [  8,   9, 100,  11],
       [ 12,  13,  14,  15]])

In [34]:
alt_b =m[0:3,0:2].copy()

In [35]:
alt_b

array([[0, 1],
       [4, 5],
       [8, 9]])

In [36]:
alt_b[2,1] = 100

In [37]:
alt_b

array([[  0,   1],
       [  4,   5],
       [  8, 100]])

In [46]:
m

array([[  0,   1,  15,   3],
       [  4,   5,   6,   7],
       [  8,   9, 100,  11],
       [ 12,  13,  14,  15]])

In [39]:
al_getir = [1,3,5]

In [44]:
a[al_getir]

array([21, 23, 25])

In [48]:
satır = np.array([0,1])
sutun = np.array([1,2])

In [49]:
m[satır,sutun]

array([1, 6])

In [54]:
k = np.arange(9).reshape(3,3)
k

array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])