In [2]:
import pandas as pd
import numpy as np

In [3]:
seri = pd.Series([122,222,333,555,444],
                index =["metin","ebru","cindy","cat","bardak"])
seri

metin     122
ebru      222
cindy     333
cat       555
bardak    444
dtype: int64

In [5]:
seri.index

Index(['metin', 'ebru', 'cindy', 'cat', 'bardak'], dtype='object')

In [6]:
seri.keys

<bound method Series.keys of metin     122
ebru      222
cindy     333
cat       555
bardak    444
dtype: int64>

In [7]:
seri.values

array([122, 222, 333, 555, 444], dtype=int64)

In [9]:
list(seri.items())

[('metin', 122), ('ebru', 222), ('cindy', 333), ('cat', 555), ('bardak', 444)]

In [11]:
"metin" in seri

True

In [14]:
"ebru" in seri

True

In [15]:
seri["ebru"]

222

# FANCY İNDEX YAKLASIMI

In [17]:
seri[["ebru","metin"]]

ebru     222
metin    122
dtype: int64

In [18]:
seri["ebru":"cat"]

ebru     222
cindy    333
cat      555
dtype: int64

# DATAFRAME LAR

In [21]:
l = np.arange(0,9).reshape((3,3))

In [22]:
l

array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

In [33]:
df = pd.DataFrame(l, columns=["col1","col2","col3"])
df

col1  col2  col3
0     0     1     2
1     3     4     5
2     6     7     8

In [37]:
df.columns= ("met1","met2","met3")
df

met1  met2  met3
0     0     1     2
1     3     4     5
2     6     7     8

In [30]:
df

met1  met2  met3
0     0     1     2
1     3     4     5
2     6     7     8

In [39]:
type(df)

pandas.core.frame.DataFrame

In [40]:
df.axes

[RangeIndex(start=0, stop=3, step=1),
 Index(['met1', 'met2', 'met3'], dtype='object')]

In [41]:
df.shape

(3, 3)

In [45]:
df.ndim

2

In [46]:
df.values

array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

In [47]:
type(df.values)

numpy.ndarray

In [61]:
df.head(0)

Empty DataFrame
Columns: [met1, met2, met3]
Index: []

In [62]:
aku = np.array([10,20,30,40,50])

In [63]:
pd.DataFrame(aku, columns= ["metin"])

metin
0     10
1     20
2     30
3     40
4     50