In [1]:
import numpy as np
m= np.random.normal(15,5,(3,3))
m
#ufunc fonksiyonu

array([[14.62480884, 14.97734198, 11.98013851],
       [11.66467342, 15.35241091, 19.59017984],
       [16.51984067, 13.6138519 , 13.08306317]])

In [2]:
m>15

array([[False, False, False],
       [False,  True,  True],
       [ True, False, False]])

In [3]:
m< 18

array([[ True,  True,  True],
       [ True,  True, False],
       [ True,  True,  True]])

In [4]:
m**2/10

array([[21.38850336, 22.43207728, 14.35237186],
       [13.60646061, 23.56965208, 38.37751462],
       [27.29051357, 18.53369635, 17.1166542 ]])

In [6]:
(m+50)/20

array([[3.23124044, 3.2488671 , 3.09900693],
       [3.08323367, 3.26762055, 3.47950899],
       [3.32599203, 3.18069259, 3.15415316]])

#cheatsheet kavramı ve googlamak kavramları iyi çalıs