5x0 + x1 = 12
1x0 + 3x1 =10 , x0, x1 nedir?

In [3]:
import numpy as np

In [6]:
a= np.array([[5,1],[1,3]])
b= np.array([12,10])

In [7]:
a

array([[5, 1],
       [1, 3]])

In [8]:
b

array([12, 10])

In [10]:
x= np.linalg.solve(a,b)
x

array([1.85714286, 2.71428571])

sonuç = x1=1.85 ve x2 = 2.71