In [3]:
import numpy as np
m=np.arange(0,30,3)
m

array([ 0,  3,  6,  9, 12, 15, 18, 21, 24, 27])

In [4]:
m[1],m[4],m[6]

(3, 12, 18)

In [5]:
al=[1,4,7]

In [6]:
m[al]

array([ 3, 12, 21])

In [44]:
k= np.arange(9).reshape((3,3))
k

array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

In [40]:
satir= np.array([2,1])
sutun = np.array([2,1]) #BENN BURAYI ANLAMADIM

In [41]:
k[sutun,satir]

array([8, 4])

In [48]:
k[0,[2,2]] #basit index, fancy index kuulanımı

array([2, 2])

In [50]:
k[0:, [2,2]] #slice index ve fancy index kuulanımı

array([[2, 2],
       [5, 5],
       [8, 8]])